server:
  port: 8081
spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mysql://jaetteoli.cswo92uen0rv.ap-northeast-2.rds.amazonaws.com/jiseop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: tjddls1920$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true