
spring:
  redis:
    host: localhost
    port: 6379

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

jpa:
  open-in-view: true
  hibernate:
    ddl-auto: update
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    use-new-id-generator-mappings: false
  database: mysql